server 
{
    listen 8080;
    index index.html;

    root /Users/sfartah/Desktop/webserv;

    location /
    {
        autoindex on;
    }

    location /cgi
    {
        allowed_method POST GET;
        cgi_pass /usr/local/bin/python3;
        cgi_extension .py;
    }

    location /upload
    {
        allowed_method POST;
        upload_store /Users/sfartah/Desktop/uploadDire/;
    }
}