server
{
    listen 8080;
    index image.png;
    root /home/sm/Desktop/webserv;
    # location /
    # {
    #     allowed_method GET ;
    #     autoindex on;
    #     upload_store /home/sm/Desktop/uploadDire;
    #     upload_store /home/sm/Desktop/x;
    # }
    location /
    {
        allowed_method POST GET;
        cgi_pass /usr/bin/python3;
        cgi_extension .py;
    }
}