server
{
    listen 8080;
    index Makefile;
    root /Users/ychedmi/Desktop/web;
    # location /
    # {
    #     allowed_method GET ;
    #     upload_store /home/sm/Desktop/x;
    # }
    location /
    {
        autoindex on;
        allowed_method POST GET;
        cgi_pass /usr/bin/python3;
        cgi_extension .py;
        upload_store /Users/ychedmi/Desktop/uploadDire;
    }
}