server {
    listen 8080;
    root /tmp/webserv_test/www;
    index index.html;
    
    # UNIQUEMENT CGI PHP
    location /cgi-bin/ {
        root /tmp/webserv_test/www/cgi-bin;
        allowed_method GET POST;
        cgi_extension .php;
        cgi_pass /usr/bin/php-cgi;
        index index.php;
    }
    
    # UNIQUEMENT CGI Python
    location /scripts/ {
        root /tmp/webserv_test/www/scripts;
        allowed_method GET POST;
        cgi_extension .py;
        cgi_pass /usr/bin/python3;
    }
}